<div class="wrap bem-zf_core-admin">
    <div id="icon-options-general" class="icon32">
        <br/>
    </div>
    <h2>Cookie Policy</h2>
</div>

<div class="brx-options_form" data-view="brx.OptionsForm" data-scope="" data-prefix="brx_CookiePolicy" style="display: none;">
    <div class="form_fields">
        <div class="form_field stretch field_policy_url" data-attach-point="fields.policy_url" data-check-required="Please fill-in Cookie Policy Url">
            <label class="width40">Cookie Policy Url:</label>
            <div class="form_field-input_box">
                <input name="policy_url" type="text" value=""/> 
            </div>
            <div class="form_field-tips"></div>
        </div>
    </div>
    <div class="button_pane">
        <button class="button button-large button-primary" data-attach-event="saveOptions">Сохранить</button>
    </div>
</div>
